import { Activity, Ambulance, HeartPulse, Tag } from "lucide-react";
import type { AdminResource } from "@/lib/admin/types";

export const casualtiesResources: AdminResource[] = [
  {
    key: "casualty-types",
    title: "Types de victimes",
    description: "Referentiel des types de victimes.",
    endpoint: "types",
    category: "casualties",
    group: "Referentiels",
    idFields: ["casualty_type_id"],
    fields: [
      { key: "code", label: "Code" },
      { key: "label", label: "Label" },
    ],
    readFields: [{ key: "casualty_type_id", hidden: true }, "code", "label"],
    icon: Tag,
  },
  {
    key: "casualty-statuses",
    title: "Statuts de victimes",
    description: "Referentiel des statuts de prise en charge.",
    endpoint: "statuses",
    category: "casualties",
    group: "Referentiels",
    idFields: ["casualty_status_id"],
    fields: [{ key: "label", label: "Label", required: true }],
    readFields: [{ key: "casualty_status_id", hidden: true }, "label"],
    icon: Activity,
  },
  {
    key: "casualties",
    title: "Victimes",
    description: "Suivi des victimes par phase d'incident.",
    endpoint: "",
    category: "casualties",
    group: "Victimes",
    idFields: ["casualty_id"],
    fields: [
      {
        key: "incident_phase_id",
        label: "Phase d'incident",
        required: true,
        reference: {
          resourceKey: "incident-phases",
          valueKey: "incident_phase_id",
          labelKey: ["phase_type.label", "incident.address"],
          placeholder: "Selectionner une phase",
        },
      },
      {
        key: "casualty_type_id",
        label: "Type",
        required: true,
        reference: {
          resourceKey: "casualty-types",
          valueKey: "casualty_type_id",
          labelKey: ["code", "label"],
          placeholder: "Selectionner un type",
        },
      },
      {
        key: "casualty_status_id",
        label: "Statut",
        required: true,
        reference: {
          resourceKey: "casualty-statuses",
          valueKey: "casualty_status_id",
          labelKey: "label",
          placeholder: "Selectionner un statut",
        },
      },
      {
        key: "reported_at",
        label: "Reporte le",
        type: "datetime",
      },
      { key: "notes", label: "Notes" },
    ],
    readFields: [
      { key: "casualty_id", hidden: true },
      "incident_phase_id",
      "casualty_type_id",
      "casualty_status_id",
      "reported_at",
      "notes",
    ],
    icon: HeartPulse,
  },
  {
    key: "casualty-transports",
    title: "Transports de victimes",
    description: "Trajets et prises en charge par véhicule.",
    endpoint: "transports",
    category: "casualties",
    group: "Transports",
    idFields: ["casualty_transport_id"],
    fields: [
      {
        key: "casualty_id",
        label: "Victime",
        required: true,
        reference: {
          resourceKey: "casualties",
          valueKey: "casualty_id",
          placeholder: "Selectionner une victime",
        },
      },
      {
        key: "vehicle_assignment_id",
        label: "Affectation véhicule",
        reference: {
          resourceKey: "vehicle-assignments",
          valueKey: "vehicle_assignment_id",
          labelKey: ["vehicle_id", "incident_phase_id"],
          placeholder: "Selectionner une affectation",
        },
      },
      {
        key: "picked_up_at",
        label: "Pris en charge le",
        type: "datetime",
      },
      {
        key: "dropped_off_at",
        label: "Depose le",
        type: "datetime",
      },
      {
        key: "picked_up_latitude",
        label: "Latitude prise en charge",
        type: "number",
      },
      {
        key: "picked_up_longitude",
        label: "Longitude prise en charge",
        type: "number",
      },
      {
        key: "dropped_off_latitude",
        label: "Latitude depot",
        type: "number",
      },
      {
        key: "dropped_off_longitude",
        label: "Longitude depot",
        type: "number",
      },
      { key: "notes", label: "Notes" },
    ],
    readFields: [
      { key: "casualty_transport_id", hidden: true },
      "casualty_id",
      "vehicle_assignment_id",
      "picked_up_at",
      "dropped_off_at",
      "picked_up_latitude",
      "picked_up_longitude",
      "dropped_off_latitude",
      "dropped_off_longitude",
      "notes",
    ],
    icon: Ambulance,
  },
];
