import {
  Boxes,
  ClipboardList,
  Layers,
  Link2,
  Package,
  Tag,
  Tags,
} from "lucide-react";
import type { AdminResource } from "@/lib/admin/types";

export const incidentsResources: AdminResource[] = [
  {
    key: "incidents",
    title: "Incidents",
    description: "Suivi des incidents et informations de localisation.",
    endpoint: "",
    category: "incidents",
    group: "Incidents",
    idFields: ["incident_id"],
    fields: [
      {
        key: "created_by_operator_id",
        label: "Operateur createur",
        reference: {
          resourceKey: "operators",
          valueKey: "operator_id",
          labelKey: "email",
          placeholder: "Selectionner un operateur",
        },
      },
      { key: "address", label: "Adresse" },
      { key: "zipcode", label: "Code postal" },
      { key: "city", label: "Ville" },
      { key: "latitude", label: "Latitude", type: "number" },
      { key: "longitude", label: "Longitude", type: "number" },
      { key: "description", label: "Description" },
      {
        key: "ended_at",
        label: "Termine le",
        type: "datetime",
      },
    ],
    readFields: [
      { key: "incident_id", hidden: true },
      "city",
      "zipcode",
      "address",
      "description",
      "created_by_operator_id",
      "created_at",
      "ended_at",
    ],
    icon: ClipboardList,
  },
  {
    key: "incident-phases",
    title: "Phases d'incident",
    description: "Phases associees aux incidents.",
    endpoint: "phases",
    category: "incidents",
    group: "Phases",
    idFields: ["incident_phase_id"],
    fields: [
      {
        key: "incident_id",
        label: "Incident",
        required: true,
        reference: {
          resourceKey: "incidents",
          valueKey: "incident_id",
          labelKey: ["city", "address"],
          placeholder: "Selectionner un incident",
        },
      },
      {
        key: "phase_type_id",
        label: "Type de phase",
        required: true,
        reference: {
          resourceKey: "incident-phase-types",
          valueKey: "phase_type_id",
          labelKey: ["code", "label"],
          placeholder: "Selectionner un type",
        },
      },
      { key: "priority", label: "Priorite", type: "integer" },
      {
        key: "started_at",
        label: "Debut",
        type: "datetime",
      },
      {
        key: "ended_at",
        label: "Fin",
        type: "datetime",
      },
    ],
    readFields: [
      { key: "incident_phase_id", hidden: true },
      "incident_id",
      "phase_type_id",
      "priority",
      "started_at",
      "ended_at",
    ],
    icon: Layers,
  },
  {
    key: "incident-phase-dependencies",
    title: "Dependances de phases",
    description: "Relations et precedences entre phases.",
    endpoint: "phase/dependencies",
    category: "incidents",
    group: "Phases",
    idFields: ["id"],
    fields: [
      {
        key: "incident_phase_id",
        label: "Phase",
        required: true,
        reference: {
          resourceKey: "incident-phases",
          valueKey: "incident_phase_id",
          labelKey: ["phase_type_id", "incident_id"],
          placeholder: "Selectionner une phase",
        },
      },
      {
        key: "depends_on_incident_phase_id",
        label: "Depend de",
        required: true,
        reference: {
          resourceKey: "incident-phases",
          valueKey: "incident_phase_id",
          labelKey: ["phase_type_id", "incident_id"],
          placeholder: "Selectionner une phase",
        },
      },
      {
        key: "kind",
        label: "Type de lien",
        required: true,
        placeholder: "CAUSE / SEQUENCE / RELATED",
      },
    ],
    readFields: [
      { key: "id", hidden: true },
      "incident_phase_id",
      "depends_on_incident_phase_id",
      "kind",
      "created_at",
    ],
    icon: Link2,
  },
  {
    key: "incident-phase-categories",
    title: "Categories de phases",
    description: "Referentiel des categories de phases.",
    endpoint: "phase/categories",
    category: "incidents",
    group: "Referentiels",
    idFields: ["phase_category_id"],
    fields: [
      { key: "code", label: "Code", required: true },
      { key: "label", label: "Label" },
    ],
    readFields: [{ key: "phase_category_id", hidden: true }, "code", "label"],
    icon: Tags,
  },
  {
    key: "incident-phase-types",
    title: "Types de phases",
    description: "Referentiel des types de phases d'incident.",
    endpoint: "phase/types",
    category: "incidents",
    group: "Referentiels",
    idFields: ["phase_type_id"],
    fields: [
      {
        key: "phase_category_id",
        label: "Categorie",
        required: true,
        reference: {
          resourceKey: "incident-phase-categories",
          valueKey: "phase_category_id",
          labelKey: ["code", "label"],
          placeholder: "Selectionner une categorie",
        },
      },
      { key: "code", label: "Code", required: true },
      { key: "label", label: "Label" },
      {
        key: "default_criticity",
        label: "Criticite par defaut",
        type: "integer",
        required: true,
      },
    ],
    readFields: [
      { key: "phase_type_id", hidden: true },
      "phase_category_id",
      "code",
      "label",
      "default_criticity",
    ],
    icon: Tag,
  },
  {
    key: "incident-vehicle-requirement-groups",
    title: "Groupes de besoins vehicules",
    description: "Regles de besoin par type de phase.",
    endpoint: "vehicle-requirement-groups",
    category: "incidents",
    group: "Besoins vehicules",
    idFields: ["group_id"],
    fields: [
      {
        key: "phase_type_id",
        label: "Type de phase",
        required: true,
        reference: {
          resourceKey: "incident-phase-types",
          valueKey: "phase_type_id",
          labelKey: ["code", "label"],
          placeholder: "Selectionner un type",
        },
      },
      { key: "label", label: "Label" },
      { key: "rule", label: "Regle", required: true, placeholder: "ALL / ANY" },
      { key: "min_total", label: "Minimum total", type: "integer" },
      { key: "max_total", label: "Maximum total", type: "integer" },
      { key: "priority", label: "Priorite", type: "integer" },
      { key: "is_hard", label: "Contrainte forte", type: "boolean" },
    ],
    readFields: [
      { key: "group_id", hidden: true },
      "phase_type_id",
      "label",
      "rule",
      "min_total",
      "max_total",
      "priority",
      "is_hard",
      "created_at",
    ],
    icon: Boxes,
  },
  {
    key: "incident-vehicle-requirements",
    title: "Besoins vehicules",
    description: "Quantites attendues par groupe et type de vehicule.",
    endpoint: "vehicle-requirements",
    category: "incidents",
    group: "Besoins vehicules",
    idFields: ["group_id", "vehicle_type_id"],
    fields: [
      {
        key: "group_id",
        label: "Groupe",
        required: true,
        reference: {
          resourceKey: "incident-vehicle-requirement-groups",
          valueKey: "group_id",
          labelKey: "label",
          placeholder: "Selectionner un groupe",
        },
      },
      {
        key: "vehicle_type_id",
        label: "Type de vehicule",
        required: true,
        reference: {
          resourceKey: "vehicle-types",
          valueKey: "vehicle_type_id",
          labelKey: ["code", "label"],
          placeholder: "Selectionner un type",
        },
      },
      { key: "min_quantity", label: "Minimum", type: "integer" },
      { key: "max_quantity", label: "Maximum", type: "integer" },
      { key: "mandatory", label: "Obligatoire", type: "boolean" },
      { key: "preference_rank", label: "Rang de preference", type: "integer" },
    ],
    updateFields: [
      { key: "min_quantity", label: "Minimum", type: "integer" },
      { key: "max_quantity", label: "Maximum", type: "integer" },
      { key: "mandatory", label: "Obligatoire", type: "boolean" },
      { key: "preference_rank", label: "Rang de preference", type: "integer" },
    ],
    readFields: [
      "group_id",
      "vehicle_type_id",
      "min_quantity",
      "max_quantity",
      "mandatory",
      "preference_rank",
      "created_at",
    ],
    icon: Package,
  },
];
