import { Boxes, MapPin, Package, Tag } from "lucide-react";
import type { AdminResource } from "@/lib/admin/types";

export const interestPointsResources: AdminResource[] = [
  {
    key: "interest-points",
    title: "Points d'intérêt",
    description: "Gestion des points d'intérêt (casernes, hôpitaux, etc.).",
    endpoint: "",
    category: "interest-points",
    group: "Points",
    idFields: ["interest_point_id"],
    fields: [
      { key: "name", label: "Nom" },
      { key: "address", label: "Adresse" },
      { key: "zipcode", label: "Code postal", type: "text" },
      { key: "city", label: "Ville" },
      { key: "latitude", label: "Latitude", type: "number" },
      { key: "longitude", label: "Longitude", type: "number" },
      {
        key: "interest_point_kind_id",
        label: "Type",
        reference: {
          resourceKey: "interest-point-kinds",
          valueKey: "interest_point_kind_id",
          labelKey: "label",
          placeholder: "Sélectionner un type",
        },
      },
    ],
    readFields: [
      { key: "interest_point_id", hidden: true },
      "name",
      "address",
      "zipcode",
      "city",
      "latitude",
      "longitude",
      "interest_point_kind_id",
    ],
    icon: MapPin,
  },
  {
    key: "interest-point-kinds",
    title: "Types de points d'intérêt",
    description: "Catégories des points d'intérêt.",
    endpoint: "kinds",
    category: "interest-points",
    group: "Référentiels",
    idFields: ["interest_point_kind_id"],
    fields: [{ key: "label", label: "Label", required: true }],
    readFields: [{ key: "interest_point_kind_id", hidden: true }, "label"],
    icon: Tag,
  },
  {
    key: "interest-point-consumable-types",
    title: "Types de consommables",
    description: "Types de consommables disponibles aux points d'intérêt.",
    endpoint: "consumable-types",
    category: "interest-points",
    group: "Consommables",
    idFields: ["interest_point_consumable_type_id"],
    fields: [{ key: "label", label: "Label", required: true }],
    readFields: [
      { key: "interest_point_consumable_type_id", hidden: true },
      "label",
    ],
    icon: Package,
  },
  {
    key: "interest-point-consumables",
    title: "Stocks de consommables",
    description: "Quantités disponibles par point d'intérêt.",
    endpoint: "consumables",
    category: "interest-points",
    group: "Consommables",
    idFields: ["interest_point_id", "interest_point_consumable_type_id"],
    fields: [
      {
        key: "interest_point_id",
        label: "Point d'intérêt",
        required: true,
        reference: {
          resourceKey: "interest-points",
          valueKey: "interest_point_id",
          labelKey: ["name", "city"],
          placeholder: "Sélectionner un point d'intérêt",
        },
      },
      {
        key: "interest_point_consumable_type_id",
        label: "Type de consommable",
        required: true,
        reference: {
          resourceKey: "interest-point-consumable-types",
          valueKey: "interest_point_consumable_type_id",
          labelKey: "label",
          placeholder: "Sélectionner un consommable",
        },
      },
      { key: "current_quantity", label: "Quantité actuelle", type: "number" },
      {
        key: "last_update",
        label: "Dernière mise à jour",
        placeholder: "2025-01-01T12:30:00Z",
      },
    ],
    updateFields: [
      { key: "current_quantity", label: "Quantité actuelle", type: "number" },
      {
        key: "last_update",
        label: "Dernière mise à jour",
        placeholder: "2025-01-01T12:30:00Z",
      },
    ],
    readFields: [
      { key: "interest_point_id", hidden: true },
      { key: "interest_point_consumable_type_id", hidden: true },
      "current_quantity",
      "last_update",
    ],
    icon: Boxes,
  },
];
