import {
  Activity,
  Boxes,
  Fuel,
  Link2,
  MapPinned,
  Package,
  SlidersHorizontal,
  Truck,
} from "lucide-react";
import type { AdminResource } from "@/lib/admin/types";

export const vehiclesResources: AdminResource[] = [
  {
    key: "vehicles",
    title: "Vehicules",
    description: "Gestion du parc de vehicules.",
    endpoint: "",
    category: "vehicles",
    group: "Flotte",
    idFields: ["vehicle_id"],
    fields: [
      {
        key: "vehicle_type_id",
        label: "Vehicle type id",
        required: true,
        reference: {
          resourceKey: "vehicle-types",
          valueKey: "vehicle_type_id",
          labelKey: ["code", "label"],
          placeholder: "Selectionner un type",
        },
      },
      { key: "immatriculation", label: "Immatriculation", required: true },
      {
        key: "energy_id",
        label: "Energy id",
        reference: {
          resourceKey: "energies",
          valueKey: "energy_id",
          labelKey: "label",
          placeholder: "Selectionner une energie",
        },
      },
      { key: "energy_level", label: "Energy level", type: "integer" },
      {
        key: "base_interest_point_id",
        label: "Base interest point id",
        reference: {
          endpoint: "interest-points",
          valueKey: "interest_point_id",
          labelKey: ["name", "city"],
          placeholder: "Selectionner un point",
        },
      },
      {
        key: "status_id",
        label: "Status id",
        reference: {
          resourceKey: "vehicle-statuses",
          valueKey: "vehicle_status_id",
          labelKey: "label",
          placeholder: "Selectionner un statut",
        },
      },
    ],
    readFields: [
      { key: "vehicle_id", hidden: true },
      "vehicle_type_id",
      "immatriculation",
      "energy_id",
      "energy_level",
      "base_interest_point_id",
      "status_id",
    ],
    icon: Truck,
  },
  {
    key: "vehicle-assignments",
    title: "Affectations de vehicules",
    description: "Liens entre vehicules et interventions.",
    endpoint: "assignments",
    category: "vehicles",
    group: "Flotte",
    idFields: ["vehicle_assignment_id"],
    fields: [
      {
        key: "vehicle_id",
        label: "Vehicle id",
        required: true,
        reference: {
          resourceKey: "vehicles",
          valueKey: "vehicle_id",
          labelKey: ["immatriculation", "vehicle_type.code"],
          placeholder: "Selectionner un vehicule",
        },
      },
      {
        key: "incident_phase_id",
        label: "Incident phase id",
        required: true,
        reference: {
          resourceKey: "incident-phases",
          valueKey: "incident_phase_id",
          labelKey: ["incident.address", "phase_type.label"],
          placeholder: "Selectionner une phase",
        },
      },
      {
        key: "assigned_at",
        label: "Assigned at",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
        required: true,
      },
      {
        key: "assigned_by_operator_id",
        label: "Assigned by operator id",
        reference: {
          resourceKey: "operators",
          valueKey: "operator_id",
          labelKey: "email",
          placeholder: "Selectionner un operateur",
        },
      },
      {
        key: "validated_at",
        label: "Validated at",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
      },
      {
        key: "validated_by_operator_id",
        label: "Validated by operator id",
        reference: {
          resourceKey: "operators",
          valueKey: "operator_id",
          labelKey: "email",
          placeholder: "Selectionner un operateur",
        },
      },
      {
        key: "unassigned_at",
        label: "Unassigned at",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
        required: false,
      },
      { key: "notes", label: "Notes" },
    ],
    updateFields: [
      { key: "incident_phase_id", label: "Incident phase id" },
      {
        key: "assigned_at",
        label: "Assigned at",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
      },
      { key: "assigned_by_operator_id", label: "Assigned by operator id" },
      {
        key: "validated_at",
        label: "Validated at",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
      },
      { key: "validated_by_operator_id", label: "Validated by operator id" },
      {
        key: "unassigned_at",
        label: "Unassigned at",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
      },
      { key: "notes", label: "Notes" },
    ],
    readFields: [
      { key: "vehicle_assignment_id", hidden: true },
      "vehicle_id",
      "incident_phase_id",
      "assigned_at",
      "assigned_by_operator_id",
      "validated_at",
      "validated_by_operator_id",
      "unassigned_at",
      "notes",
    ],
    icon: Link2,
  },
  {
    key: "vehicle-position-logs",
    title: "Positions de vehicules",
    description: "Historique des positions GPS.",
    endpoint: "position-logs",
    category: "vehicles",
    group: "Flotte",
    idFields: ["vehicle_position_id"],
    fields: [
      {
        key: "vehicle_id",
        label: "Vehicle id",
        required: true,
        reference: {
          resourceKey: "vehicles",
          valueKey: "vehicle_id",
          labelKey: "immatriculation",
          placeholder: "Selectionner un vehicule",
        },
      },
      { key: "latitude", label: "Latitude", type: "number", required: true },
      { key: "longitude", label: "Longitude", type: "number", required: true },
      {
        key: "timestamp",
        label: "Timestamp",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
        required: true,
      },
    ],
    readFields: [
      { key: "vehicle_position_id", hidden: true },
      "vehicle_id",
      "latitude",
      "longitude",
      "timestamp",
    ],
    updateFields: [
      { key: "latitude", label: "Latitude", type: "number" },
      { key: "longitude", label: "Longitude", type: "number" },
      {
        key: "timestamp",
        label: "Timestamp",
        placeholder: "2025-01-01T12:30:00Z",
        type: "datetime",
      },
    ],
    supportsDelete: false,
    icon: MapPinned,
  },
  {
    key: "vehicle-consumable-types",
    title: "Types de consommables",
    description: "Consommables utilisables par les vehicules.",
    endpoint: "consumables/types",
    category: "vehicles",
    group: "Consommables",
    idFields: ["vehicle_consumable_type_id"],
    fields: [
      { key: "label", label: "Label", required: true },
      { key: "unit", label: "Unite" },
    ],
    readFields: [
      { key: "vehicle_consumable_type_id", hidden: true },
      "label",
      "unit",
    ],
    icon: Package,
  },
  {
    key: "vehicle-type-consumable-specs",
    title: "Specifications consommables",
    description: "Capacites par type de vehicule.",
    endpoint: "/consumables/specs",
    category: "vehicles",
    group: "Consommables",
    idFields: ["vehicle_type_id", "consumable_type_id"],
    fields: [
      {
        key: "vehicle_type_id",
        label: "Vehicle type id",
        required: true,
        reference: {
          resourceKey: "vehicle-types",
          valueKey: "vehicle_type_id",
          labelKey: ["code", "label"],
          placeholder: "Selectionner un type",
        },
      },
      {
        key: "consumable_type_id",
        label: "Consumable type id",
        required: true,
        reference: {
          resourceKey: "vehicle-consumable-types",
          valueKey: "vehicle_consumable_type_id",
          labelKey: "label",
          placeholder: "Selectionner un consommable",
        },
      },
      { key: "capacity_quantity", label: "Capacity qty", type: "number" },
      { key: "initial_quantity", label: "Initial qty", type: "number" },
      { key: "is_applicable", label: "Is applicable", type: "boolean" },
    ],
    updateFields: [
      { key: "capacity_quantity", label: "Capacity qty", type: "number" },
      { key: "initial_quantity", label: "Initial qty", type: "number" },
      { key: "is_applicable", label: "Is applicable", type: "boolean" },
    ],
    readFields: [
      { key: "vehicle_type_id", hidden: true },
      { key: "consumable_type_id", hidden: true },
      "capacity_quantity",
      "initial_quantity",
      "is_applicable",
    ],
    icon: SlidersHorizontal,
  },
  {
    key: "vehicle-consumables-stock",
    title: "Stocks de consommables",
    description: "Quantites disponibles par vehicule.",
    endpoint: "consumables/stock",
    category: "vehicles",
    group: "Consommables",
    idFields: ["vehicle_id", "consumable_type_id"],
    fields: [
      {
        key: "vehicle_id",
        label: "Vehicle id",
        required: true,
        reference: {
          resourceKey: "vehicles",
          valueKey: "vehicle_id",
          labelKey: "immatriculation",
          placeholder: "Selectionner un vehicule",
        },
      },
      {
        key: "consumable_type_id",
        label: "Consumable type id",
        required: true,
        reference: {
          resourceKey: "vehicle-consumable-types",
          valueKey: "vehicle_consumable_type_id",
          labelKey: "label",
          placeholder: "Selectionner un consommable",
        },
      },
      { key: "current_quantity", label: "Current qty", type: "number" },
    ],
    updateFields: [
      { key: "current_quantity", label: "Current qty", type: "number" },
    ],
    readFields: [
      { key: "vehicle_id", hidden: true },
      { key: "consumable_type_id", hidden: true },
      "current_quantity",
      "last_update",
    ],
    icon: Boxes,
  },
  {
    key: "vehicle-types",
    title: "Types de vehicules",
    description: "Catalogue des types disponibles.",
    endpoint: "types",
    category: "vehicles",
    group: "Referentiels",
    idFields: ["vehicle_type_id"],
    fields: [
      { key: "code", label: "Code", required: true },
      { key: "label", label: "Label", required: true },
    ],
    readFields: [{ key: "vehicle_type_id", hidden: true }, "code", "label"],
    icon: Truck,
  },
  {
    key: "energies",
    title: "Energies",
    description: "Sources d'energie des vehicules.",
    endpoint: "energies",
    category: "vehicles",
    group: "Referentiels",
    idFields: ["energy_id"],
    fields: [{ key: "label", label: "Label", required: true }],
    readFields: [{ key: "energy_id", hidden: true }, "label"],
    icon: Fuel,
  },
  {
    key: "vehicle-statuses",
    title: "Statuts de vehicules",
    description: "Etat courant d'un vehicule.",
    endpoint: "statuses",
    category: "vehicles",
    group: "Referentiels",
    idFields: ["vehicle_status_id"],
    fields: [{ key: "label", label: "Label", required: true }],
    readFields: [{ key: "vehicle_status_id", hidden: true }, "label"],
    icon: Activity,
  },
];
