import {
  Activity,
  Boxes,
  Fuel,
  Link2,
  MapPinned,
  Package,
  SlidersHorizontal,
  Truck,
} from "lucide-react";
import type { AdminResource } from "@/lib/admin/types";

export const vehiclesResources: AdminResource[] = [
  {
    key: "energies",
    title: "Energies",
    description: "Sources d'energie des vehicules.",
    endpoint: "energies",
    category: "vehicles",
    group: "Referentiels",
    idFields: ["energy_id"],
    fields: [{ key: "label", label: "Label", required: true }],
    readFields: ["energy_id", "label"],
    icon: Fuel,
  },
  {
    key: "vehicle-types",
    title: "Types de vehicules",
    description: "Catalogue des types disponibles.",
    endpoint: "types",
    category: "vehicles",
    group: "Referentiels",
    idFields: ["vehicle_type_id"],
    fields: [
      { key: "code", label: "Code", required: true },
      { key: "label", label: "Label", required: true },
    ],
    readFields: ["vehicle_type_id", "code", "label"],
    icon: Truck,
  },
  {
    key: "vehicle-statuses",
    title: "Statuts de vehicules",
    description: "Etat courant d'un vehicule.",
    endpoint: "statuses",
    category: "vehicles",
    group: "Referentiels",
    idFields: ["vehicle_status_id"],
    fields: [{ key: "label", label: "Label", required: true }],
    readFields: ["vehicle_status_id", "label"],
    icon: Activity,
  },
  {
    key: "vehicle-consumable-types",
    title: "Types de consommables",
    description: "Consommables utilisables par les vehicules.",
    endpoint: "/consumables/types",
    category: "vehicles",
    group: "Referentiels",
    idFields: ["vehicle_consumable_type_id"],
    fields: [
      { key: "label", label: "Label", required: true },
      { key: "unit", label: "Unite" },
    ],
    readFields: ["vehicle_consumable_type_id", "label", "unit"],
    icon: Package,
  },
  {
    key: "vehicles",
    title: "Vehicules",
    description: "Gestion du parc de vehicules.",
    endpoint: "/",
    category: "vehicles",
    group: "Flotte",
    idFields: ["vehicle_id"],
    fields: [
      { key: "vehicle_type_id", label: "Vehicle type id", required: true },
      { key: "immatriculation", label: "Immatriculation", required: true },
      { key: "energy_id", label: "Energy id" },
      { key: "energy_level", label: "Energy level", type: "integer" },
      { key: "base_interest_point_id", label: "Base interest point id" },
      { key: "status_id", label: "Status id" },
    ],
    readFields: [
      "vehicle_id",
      "vehicle_type_id",
      "immatriculation",
      "energy_id",
      "energy_level",
      "base_interest_point_id",
      "status_id",
    ],
    icon: Truck,
  },
  {
    key: "vehicle-assignments",
    title: "Affectations de vehicules",
    description: "Liens entre vehicules et interventions.",
    endpoint: "assignments",
    category: "vehicles",
    group: "Flotte",
    idFields: ["vehicle_assignment_id"],
    fields: [
      { key: "vehicle_id", label: "Vehicle id", required: true },
      { key: "intervention_id", label: "Intervention id", required: true },
      { key: "incident_phase_id", label: "Incident phase id" },
      {
        key: "unassigned_at",
        label: "Unassigned at",
        placeholder: "2025-01-01T12:30:00Z",
      },
      { key: "assigned_by_operator_id", label: "Assigned by operator id" },
    ],
    updateFields: [
      { key: "incident_phase_id", label: "Incident phase id" },
      {
        key: "unassigned_at",
        label: "Unassigned at",
        placeholder: "2025-01-01T12:30:00Z",
      },
      { key: "assigned_by_operator_id", label: "Assigned by operator id" },
    ],
    readFields: [
      "vehicle_assignment_id",
      "vehicle_id",
      "intervention_id",
      "incident_phase_id",
      "assigned_at",
      "unassigned_at",
      "assigned_by_operator_id",
    ],
    icon: Link2,
  },
  {
    key: "vehicle-position-logs",
    title: "Positions de vehicules",
    description: "Historique des positions GPS.",
    endpoint: "position-logs",
    category: "vehicles",
    group: "Flotte",
    idFields: ["vehicle_position_id"],
    fields: [
      { key: "vehicle_id", label: "Vehicle id", required: true },
      { key: "latitude", label: "Latitude", type: "number", required: true },
      { key: "longitude", label: "Longitude", type: "number", required: true },
      {
        key: "timestamp",
        label: "Timestamp",
        placeholder: "2025-01-01T12:30:00Z",
      },
    ],
    readFields: [
      "vehicle_position_id",
      "vehicle_id",
      "latitude",
      "longitude",
      "timestamp",
    ],
    supportsUpdate: false,
    supportsDelete: false,
    icon: MapPinned,
  },
  {
    key: "vehicle-type-consumable-specs",
    title: "Specifications consommables",
    description: "Capacites par type de vehicule.",
    endpoint: "/consumables/specs",
    category: "vehicles",
    group: "Consommables",
    idFields: ["vehicle_type_id", "consumable_type_id"],
    fields: [
      { key: "vehicle_type_id", label: "Vehicle type id", required: true },
      {
        key: "consumable_type_id",
        label: "Consumable type id",
        required: true,
      },
      { key: "capacity_quantity", label: "Capacity qty", type: "number" },
      { key: "initial_quantity", label: "Initial qty", type: "number" },
      { key: "is_applicable", label: "Is applicable", type: "boolean" },
    ],
    updateFields: [
      { key: "capacity_quantity", label: "Capacity qty", type: "number" },
      { key: "initial_quantity", label: "Initial qty", type: "number" },
      { key: "is_applicable", label: "Is applicable", type: "boolean" },
    ],
    readFields: [
      "vehicle_type_id",
      "consumable_type_id",
      "capacity_quantity",
      "initial_quantity",
      "is_applicable",
    ],
    icon: SlidersHorizontal,
  },
  {
    key: "vehicle-consumables-stock",
    title: "Stocks de consommables",
    description: "Quantites disponibles par vehicule.",
    endpoint: "/consumables/stock",
    category: "vehicles",
    group: "Consommables",
    idFields: ["vehicle_id", "consumable_type_id"],
    fields: [
      { key: "vehicle_id", label: "Vehicle id", required: true },
      {
        key: "consumable_type_id",
        label: "Consumable type id",
        required: true,
      },
      { key: "current_quantity", label: "Current qty", type: "number" },
    ],
    updateFields: [
      { key: "current_quantity", label: "Current qty", type: "number" },
    ],
    readFields: [
      "vehicle_id",
      "consumable_type_id",
      "current_quantity",
      "last_update",
    ],
    icon: Boxes,
  },
];
